# Generated by Django 2.2.7 on 2020-03-08 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_auto_20200213_0436'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
